//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecuritySafeZone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Reports = new HashSet<Report>();
        }

        public int Uid { get; set; }
        [Required(ErrorMessage = "Please Enter Name")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Please Enter CNIC")]
        public string CNIC { get; set; }
        [Required(ErrorMessage = "Please Enter EmailAddress")]
        [EmailAddress]//@gmail.com
        public string Email { get; set; }
        [Required(ErrorMessage = "Enter Contact number")]
        public string ContactNo { get; set; }
        [Required(ErrorMessage = "Please Enter Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public int status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
    }
}
